[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r matematik-soru-deposu/requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd matematik-soru-deposu/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
